server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucketName: www-zsh0225-top-oss-bucket-test
      access-key: ************************************
      secret-key: &******************************

  application:
    name: OSSService
